### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/ruby-rocks#15]
Write ruby code for binary search.

**Comment by dhananjay425** [comment]
assign me i will do it

**Comment by UstitvaG** [comment]
hello, i would like to work on this issue. 
could you assign this issue to me?

**Comment by Arika008** [comment]
Please check my PR #21

**Comment by ShehrozIrfan** [comment]
@dhananjay425 
@astitva0011 
Assigned.
