### ISSUE TITLE
Add contributors list in readme file

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/ruby-rocks#22]
We need to add the contributors list in the readme file. The heading will be:
### Our Valuable Contributors
After the heading there will be a list of contributors.

**Comment by Omm2005** [comment]
I can do this!

**Comment by ShehrozIrfan** [comment]
@Omm2005 
Assigned.

**Comment by Omm2005** [comment]
Hey, I have added a contributor's name check on a pull request "Updated Readme" give me the name of the contributors there. 
@ShehrozIrfan Look at it, please!
