### ISSUE TITLE
Add two numbers

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/ruby-rocks#3]
Write a ruby code to add two numbers.

**Comment by riteshsoni123** [comment]
Hello @ShehrozIrfan I would like to solve this issue. Can you please assign this to me?

**Comment by sohampathak1234** [comment]
Hey @ShehrozIrfan , I am happy to work on this issue. Please assign me this issue.

**Comment by ShehrozIrfan** [comment]
@riteshsoni123 
@sohampathak1234 
Assigned.
