### ISSUE TITLE
Implement stack 

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/ruby-rocks#33]
We need to implement the stack using ruby.

**Comment by navaneethkp36** [comment]
hi @ShehrozIrfan I would like to contribute to this

**Comment by amardeep911** [comment]
Plz assignt this to me

**Comment by ShehrozIrfan** [comment]
@navaneethkp36 
@amardeep911 
Assigned.

**Comment by prateekverma457** [comment]
please assign this to me

**Comment by ShehrozIrfan** [comment]
@Prateekgeeks 
Assigned.

**Comment by navaneethkp36** [comment]
@ShehrozIrfan un-assigning myself since I wont be able to complete this due to other tasks.
