### ISSUE TITLE
Implement Singly Linked List 

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/ruby-rocks#35]
We need to implement the singly linked list using ruby.

**Comment by navaneethkp36** [comment]
hi @ShehrozIrfan . I would like to contribute to this

**Comment by ShehrozIrfan** [comment]
@navaneethkp36 
Assigned.

**Comment by akash-1107** [comment]
Please assign this to me

**Comment by ShehrozIrfan** [comment]
@akash-1107 
Assigned.

**Comment by navaneethkp36** [comment]
@ShehrozIrfan un-assigning myself since I wont be able to complete this due to other tasks.

**Comment by kunaldhongade** [comment]
@ShehrozIrfan I would like to work on that, please assign me this task

**Comment by ShehrozIrfan** [comment]
@kunaldhongade 
Assigned.
