### ISSUE TITLE
Implement Doubly Linked List

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/ruby-rocks#36]
We need to implement the doubly linked list using ruby.

**Comment by Hussain6** [comment]
@ShehrozIrfan Can you assign this issue to me I would like to contribute with a doubly linked list with operations of Insert, Delete, Update & Display output in CPP.

**Comment by ShehrozIrfan** [comment]
@Hussain6 
You need to do this in ruby only.

**Comment by SakshiMishra1** [comment]
@ShehrozIrfan please assign this issue to me.

**Comment by SakshiMishra1** [comment]
Kindly check PR #44

**Comment by ShehrozIrfan** [comment]
> Kindly check PR #44

yes merged.

**Comment by ShehrozIrfan** [comment]
> @ShehrozIrfan Can you assign this issue to me I would like to contribute with a doubly linked list with operations of Insert, Delete, Update & Display output in CPP.

assigned.

**Comment by sp-gits** [comment]
**can you assign this issue to me ?**

**Comment by ShehrozIrfan** [comment]
@snehasish-pathak 
Assigned.

**Comment by riteshsoni123** [comment]
Hello @ShehrozIrfan I would like to work on this issue. Can you assign this to me?

**Comment by ShehrozIrfan** [comment]
@riteshsoni123 
Assigned.
