### ISSUE TITLE
Updates to Readme file

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/ruby-rocks#39]
Right now we've 10+ contributors, but in the contributors section in readme file, it is only showing 9 contributors.
We need to correct this, like whenever there is a new contributor the list is updated automatically.

**Comment by najeebkp** [comment]
hi @ShehrozIrfan please assign this to me

**Comment by navaneethkp36** [comment]
hi @ShehrozIrfan I would like to contribute to this

**Comment by ShehrozIrfan** [comment]
@navaneethkp36 
Assigned.

**Comment by navaneethkp36** [comment]
hi @ShehrozIrfan Seems like this is already added using `contrib.rocks`. Can you please check and confirm.

**Comment by ShehrozIrfan** [comment]
Yes @navaneethkp36 it is already added.
Thanks.
