### ISSUE TITLE
Check palindrome string

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/ruby-rocks#4]
Write a ruby code to check if the string is palindrome or not.

**Comment by riteshsoni123** [comment]
Hello @ShehrozIrfan I would like to solve this issue. Can you please assign this to me ?

**Comment by sohampathak1234** [comment]
Hello @ShehrozIrfan. Can you assign me this issue?

**Comment by ShehrozIrfan** [comment]
@riteshsoni123 
@sohampathak1234 
Assigned.
