### ISSUE TITLE
Factorial of number

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/ruby-rocks#5]
Write ruby code for factorial of a number.

**Comment by AnshumanGoel** [comment]
@ShehrozIrfan Can you assign it to me
Thank you

**Comment by AnshumanGoel** [comment]
I have sent a Pull Request for the same Kindly check it and Merge it
Thank you

**Comment by sohampathak1234** [comment]
Hey @ShehrozIrfan. I am excited to work on this issue. 
Kindly Assign me this issue.

**Comment by ShehrozIrfan** [comment]
@AnshumanGoel 
@sohampathak1234 
Assigned.
