### ISSUE TITLE
Multiply two numbers

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/ruby-rocks#6]
Write ruby code for multiplying two numbers.

**Comment by Hegde2002** [comment]
Sir, can you please assign this issue to me

**Comment by sohampathak1234** [comment]
Hello @ShehrozIrfan. Kindly assign me this issue.

**Comment by ShehrozIrfan** [comment]
@Hegde2002 
@sohampathak1234 
Assigned.
