### ISSUE TITLE
Swap two numbers

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/ruby-rocks#7]
Write ruby code for swapping two numbers.
`BONUS`: Do this using two variables only

**Comment by yash-sharma13** [comment]
I'll do it

**Comment by dhananjay425** [comment]
Assign me I will do it

**Comment by Mudrikaa29** [comment]
I'll do it.

**Comment by ShehrozIrfan** [comment]
@yash-sharma13 
@dhananjay425 
@Mudrikaa29 
Assigned.
