### ISSUE TITLE
Fibonacci Series

### ISSUE THREAD

**Issue by ShehrozIrfan** [ShehrozIrfan/ruby-rocks#8]
Write ruby code for Fibonacci series.

**Comment by kunalsingh1301** [comment]
can you assign me @ShehrozIrfan

**Comment by kunalsingh1301** [comment]
https://github.com/kunalsingh1301/fibonaci_ruby.git

**Comment by ShehrozIrfan** [comment]
@kunalsingh1301 
Assigned.
